### ISSUE TITLE
Qiita のミニマム構成に必要な機能を考える

### ISSUE THREAD

**Issue by yuta-ushijima** [yuta-ushijima/qiita_clone#2]
## 概要
最低限アプリとして稼働するために必要な機能を考える

**Comment by yuta-ushijima** [comment]
### ユーザー系

### サービス全般

**Comment by mc-chinju** [comment]
ユーザー一覧ページはありました？ちょっともう一度考えてみてください！

**Comment by yuta-ushijima** [comment]
> ユーザー一覧ページはありました？

コミュニティタブを開くと、ドロップダウンメニューにあったので、
そちらで確認した次第ですー！

**Comment by mc-chinju** [comment]
あー、なるほど。個人的にはこの機能必須じゃないと思いますが、ひとまず了解ですー。


ただ、それ以前に記事一覧は入れておかないとまずいのでは？

**Comment by yuta-ushijima** [comment]
> それ以前に記事一覧は入れておかないとまずい

よく考えたらそうですよね。。ありがとうございます！

>「最低限」にしてはこれでも機能が多い
> 本当に最低限の機能を更にピックアップ
> その上で実装順序つけてみてください。

上記了解です！やってみます！

**Comment by yuta-ushijima** [comment]
## 最低限機能のピックアップ
- [ ] ホーム画面
- [ ] 記事の閲覧/投稿/編集/削除
- [ ] ログイン/ログアウト機能
- [ ] 投稿記事一覧
- [ ] ユーザー同士のいいね機能
- [ ] ユーザー登録

## 実装順序
1. ユーザー登録
1. ログイン/ログアウト機能
1. 記事の閲覧/投稿/編集/削除
1. 投稿記事一覧
1. ユーザー同士のいいね機能

こんな感じでどうでしょうか？

**Comment by mc-chinju** [comment]
いいね機能はオプションな気もしますが、優先順位低めなのでこれでよさそうですね！

**Comment by mc-chinju** [comment]
3と4は逆でもいいですよ

**Comment by yuta-ushijima** [comment]
> 3と4は逆でもいい

了解です！逆でいってみます！

**Comment by mc-chinju** [comment]
はーい！まぁ細かいところなのであまり気にしなくて大丈夫です！
