### ISSUE TITLE
最低限必要な機能を実装するために必要な DB 設計をする

### ISSUE THREAD

**Issue by yuta-ushijima** [yuta-ushijima/qiita_clone#3]
## 概要
#2 で作成した必要最低限の機能を実装するために必要なDB設計を行う。

## 工数目安
* 3人日(=24H)

## 理想(工数目安の1/5)
* 0.6人日(=5H)

## 最低限機能のピックアップ
- [ ] ホーム画面
- [ ] 投稿の閲覧/投稿/編集/削除
- [ ] ログイン/ログアウト機能
- [ ] 投稿記事一覧
- [ ] ユーザー同士のいいね機能
- [ ] ユーザー登録

**Comment by yuta-ushijima** [comment]
## ユーザーのDB設計

### はじめに
* 手書きにて、ユーザー設計のアイデア出しをおこう
* ある程度手書きで書いたら、画像を添付

**Comment by yuta-ushijima** [comment]
## 第一弾ドラフト(かかった工数: 45分)

第一弾のドラフト書いてみました！

![er _1](https://user-images.githubusercontent.com/29375012/43585084-27e3ccda-969f-11e8-8e55-160734341345.jpg)

**Comment by yuta-ushijima** [comment]
## ER図ドラフト第二弾

以下それぞれの関係図を記入しました！

* ユーザー
* 投稿記事
* コメント
* タグ
* いいね
* コミュニティ
* アドベントカレンダー

![er _2](https://user-images.githubusercontent.com/29375012/43643448-451e880e-9766-11e8-8c90-832d3e6d1128.jpg)

**Comment by yuta-ushijima** [comment]
## [WIP]カラム作成
https://erdplus.com/#/edit-diagram/626469

**Comment by mc-chinju** [comment]
多 は * で表すようにした方がいいですよー

**Comment by yuta-ushijima** [comment]
> 多 は * で表すようにした方がいい

ありがとうございます！今後そのように記述するクセをつけるようにしますね！

**Comment by mc-chinju** [comment]
ER図、一般公開はされないようなので、完成されたらスクショなり貼っていただけると嬉しいです！

**Comment by yuta-ushijima** [comment]
>ER図、一般公開はされない

なるほど！了解です！

現状、カラムだけですが、こんな感じですー！

![2018-08-04 23 53 54](https://user-images.githubusercontent.com/29375012/43677724-d35cb146-9841-11e8-9195-6110a6e370af.png)

**Comment by mc-chinju** [comment]
なるほど、このサービス、データ型の入力はできないんですかね？

**Comment by yuta-ushijima** [comment]
データ型の入力はできるんですが、ER図には表示されない見たいですねー。

DDLはexportできるんですけどね。。

```sql
CREATE TABLE Users
(
  id INT NOT NULL,
  article_id INT NOT NULL,
  like_id INT NOT NULL,
  first_name CHAR NOT NULL,
  last_name CHAR NOT NULL,
  password INT NOT NULL,
  password_confirm INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Articles
(
  id INT NOT NULL,
  content VARCHAR NOT NULL,
  user_id INT NOT NULL,
  comment_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Likes
(
  id INT NOT NULL,
  user_id INT NOT NULL,
  article_id INT NOT NULL,
  like_count INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Comments
(
  id INT NOT NULL,
  user_id INT NOT NULL,
  comment VARCHAR NOT NULL,
  PRIMARY KEY (id)
);
```

だったらmarkdownとかで書いた方がいい気もしますが^^;

**Comment by mc-chinju** [comment]
あ、DDL 出せるんですね！セットで出してもらえれば、アドバイスできるのでこれでいきましょー！

ちなみにですが、ER図作成で一番よく使われているのは [Mysql workbench](https://www.mysql.com/jp/products/workbench/ ) だと思います！（僕はほとんど使ったことないです。なので、今使われているもので大丈夫ですw）

`Comments` の `comment` column は混乱の元なのでやめた方がいいと思いますよ。`body` あたりがいいんじゃないでしょうか。

そうでないと、以下のようになります。

```rb
comment = Comment.new(comment: "aaa")
puts comment.comment
```

ちょっと何言ってるかわかりにくいですよねw

**Comment by mc-chinju** [comment]
`title` と `body` は column でもセットで使われることが多いので豆知識として覚えておくと便利です。

**Comment by yuta-ushijima** [comment]
> セットで出してもらえれば、アドバイスできるのでこれでいきましょー！

了解しました！これで出していきます！

>ER図作成で一番よく使われているのは Mysql workbench 

僕も調べてみたんですけど、やっぱり一番使われているんですね！
この辺は参画するプロジェクトだったり、好みとかによりますよねー。

>Comments の comment column は混乱の元なのでやめた方がいい
ちょっと何言ってるかわかりにくい

!!!確かに、コード書くとき混乱しますね。。修正します！

**Comment by yuta-ushijima** [comment]
最低限実装に必要なColumnのER図とDDLを作成しました！

## ColumnのER図

![2018-08-05 15 38 10](https://user-images.githubusercontent.com/29375012/43683389-9835aee0-98c5-11e8-91cb-db281c9822f3.png)



## DDL

```sql
CREATE TABLE Users
(
  id INT NOT NULL,
  first_name CHAR NOT NULL,
  last_name CHAR NOT NULL,
  password INT NOT NULL,
  password_confirm INT NOT NULL,
  like_id INT,
  article_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (like_id) REFERENCES Likes(id),
  FOREIGN KEY (article_id) REFERENCES Articles(id)
);

CREATE TABLE Articles
(
  id INT NOT NULL,
  body VARCHAR NOT NULL,
  comment_id INT,
  title CHAR NOT NULL,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Likes
(
  id INT NOT NULL,
  like_count INT,
  article_id INT,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (article_id) REFERENCES Articles(id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Comments
(
  id INT NOT NULL,
  body VARCHAR,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);
```

**Comment by mc-chinju** [comment]
ER 図、線が重なっていて見づらいです >< （だいたいわかりますが）

`likes` table の `like_count` は不要じゃないかと思います。（理由考えてみてください）
`users` は足りない column があるように思いますが、まぁ実装時にわかる気がするのでとりあえず大丈夫です。

ER図作成に関してはこれでほぼほぼおっけーですので、次のタスク進めましょう！

**Comment by yuta-ushijima** [comment]
>ER 図、線が重なっていて見づらいです

すいません！見やすさも考慮すべきでした。。

今度は見やすくなったと思いますが、どうでしょうか？

### ER図
![2018-08-05 16 25 58](https://user-images.githubusercontent.com/29375012/43683718-451a82a6-98cc-11e8-9756-2da9b120116e.png)

### DDL
CREATE TABLE Users
(
  id INT NOT NULL,
  first_name CHAR NOT NULL,
  last_name CHAR NOT NULL,
  password INT NOT NULL,
  password_confirm INT NOT NULL,
  like_id INT,
  article_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (like_id) REFERENCES Likes(id),
  FOREIGN KEY (article_id) REFERENCES Articles(id)
);

CREATE TABLE Articles
(
  id INT NOT NULL,
  body VARCHAR NOT NULL,
  comment_id INT,
  title CHAR NOT NULL,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Likes
(
  id INT NOT NULL,
  article_id INT,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (article_id) REFERENCES Articles(id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Comments
(
  id INT NOT NULL,
  body VARCHAR,
  user_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);
 

>likes table の like_count は不要じゃないかと思います。（理由考えてみてください）

これも、Adventcalendarsと同じで、「誰が、どの記事に対して、いいねをしたか」はAjaxで実装する必要があるけれど、いいねの数自体をDBに保存する必要はないからです？

>users は足りない column があるように思います

なるほど！実装しながら足りなかったcolumnについては適宜追記するようにします！

>ER図作成に関してはこれでほぼほぼおっけー

了解です！次のタスクに進んでいきます！

**Comment by mc-chinju** [comment]
> 今度は見やすくなったと思いますが、どうでしょうか？

👍 

> これも、Adventcalendarsと同じで、「誰が、どの記事に対して、いいねをしたか」はAjaxで実装する必要があるけれど、いいねの数自体をDBに保存する必要はないからです？

Ajax かどうかはあまり関係がないですね・

例えば、id: 1 の article に対して、いいねがいくつついているかをカウントするときは、

```rb
article = Article.find(1)
article.likes.count
```

つまり、紐づいている likes レコードの数が likes_count にあたりますよね。
1 つのレコードが likes_count column を持っていたとしても、特に意味を持たないんです。

**Comment by yuta-ushijima** [comment]
DB設計についてのタスクって、あとは使用するRDBSの種類とかかなと思いますが、どうでしょうか？

**Comment by mc-chinju** [comment]
mysql でいいと思いますよ。普通に使ってるところ多いですし。

**Comment by yuta-ushijima** [comment]
なるほど！じゃあmysqlでやっていこうと思います！
