### ISSUE TITLE
クローンアプリ作成におけるスケジュール（見積もり）

### ISSUE THREAD

**Issue by yuta-ushijima** [yuta-ushijima/qiita_clone#4]
## 概要
* クローンアプリ作成における見積もりを決める

## 工数
* 1人日 = 8H
* バッファ = 見積もり工数の1.5倍
* 見積もり工数は、バッファ込み

**Comment by yuta-ushijima** [comment]
## 設計

* DB設計...3人日
* API設計....3人日

## 実装

 * ログイン/ログアウト機能...2人日
 * 記事の閲覧/投稿/編集/削除...3人日
 * ユーザー一覧...1人日
 * 記事のストック...3人日
 * 公開ページの閲覧...2人日
 * ユーザー同士のいいね機能...3人日
 * ユーザー登録...3人日

## テスト

 * ログイン/ログアウト機能のテスト...2人日
 * 記事の閲覧/投稿/編集/削除...3人日
 * ユーザー一覧...1人日
 * 記事のストック...3人日
 * 公開ページの閲覧...2人日
 * ユーザー同士のいいね機能...3人日
 * ユーザー登録...3人日


## 合計

40人日 = 320H 
日数にすると、約13日

**Comment by mc-chinju** [comment]
バッファ込みならこんなもんですね！

設計は一番重要なところなのでもう少し多めに見積もっても大丈夫な気はします。

あとは、実際やってみてどうなるかもメモしていきましょう。

**Comment by yuta-ushijima** [comment]
> 設計は一番重要なところなのでもう少し多めに見積もっても大丈夫

ありがとうございます！設計の箇所はそれぞれ2人日ほど増やしました！
大体これくらいですかね？

**Comment by mc-chinju** [comment]
はいー、それで大丈夫かと思いますー！

見積もりの5倍くらいのスピードでやりきる気持ちで取り組みましょう！

**Comment by yuta-ushijima** [comment]
q

**Comment by yuta-ushijima** [comment]
テスト

**Comment by yuta-ushijima** [comment]
test

**Comment by yuta-ushijima** [comment]
test
