### ISSUE TITLE
Railsで作り始める際にやるべきタスクの順序を書き出す

### ISSUE THREAD

**Issue by yuta-ushijima** [yuta-ushijima/qiita_clone#5]
## 概要
rails で作り始める際にやるべきタスクの順序について、リストアップする

## 最低限機能のピックアップ
- [ ] ホーム画面
- [ ] 投稿の閲覧/投稿/編集/削除
- [ ] ログイン/ログアウト機能
- [ ] 投稿記事一覧
- [ ] ユーザー同士のいいね機能
- [ ] ユーザー登録

## 実装順序
1. ユーザー登録
1. ログイン/ログアウト機能
1. 投稿一覧
1. 投稿の閲覧/投稿/編集/削除
1. ユーザー同士のいいね機能

**Comment by yuta-ushijima** [comment]
## タスクリスト
- [ ] ~~dockerfileの作成~~
- [x] Gemの選定
- [x] RSpecの設定
- [ ] 実装順序に沿って実装開始

もっと粒度細い方がいいですかね？

**Comment by mc-chinju** [comment]
いえ、こんなもんでいいでしょう！
Dockerfile の作成はもう少し先でもいいと思いますよ。（すぐできるならいいですが）

gem選定からはじめてみましょうか。

**Comment by yuta-ushijima** [comment]
## gemの選定

### 実行コマンド
* foreman

### DB
* mysql2

### ログイン
* devise
* devise-i18n

### テスト
* rspec

### デバッグ
* pry
* better_errors

### 設定ファイル
* dotenv-rails
* config
* enum_help

### UI
* semantic-ui

最低限実装に必要なのはこれくらいですかね？

**Comment by mc-chinju** [comment]
> foreman

好みで入れてください。必須ではないです。

> pry
> better_errors

`binding.pry` するなら `byebug` ですかね。 `better_errors` は好みで。

> dotenv-rails
> config

定数管理は global の方がオススメです。

> enum_help

好みですが、 `enumerize` よさそうですよ。

issue で質問するのではなく、このあたりは PR 出しちゃっていいっす！そこで見れます！

**Comment by yuta-ushijima** [comment]
>issue で質問するのではなく、このあたりは PR 出しちゃっていい

わかりましたー！

この辺は直接PRで出します！いただいた返答を参考にproject作っていきます！
